### ISSUE TITLE
DRY CSS

### ISSUE THREAD

**Issue by jordanwillis** [ahmadsanusi/My_Time#4]
Your CSS looks pretty good!  One technique that you should follow to ensure you are writing the best possible code is the DRY (don't repeat yourself) principle.  Basically, the point is to remove any cases where you have duplicated properties/styles throughout your stylesheet.

For example, I noticed some duplicated font related and flex container related properties across many different selectors in your CSS.  There are a few techniques to prevent the duplication such as factoring out the repeated properties into a single class that you can repeat throughout your css or making use of combo selector rules to apply the same property to many different classes/elements.  Or another technique is to define your repeated properties in a selector that is more generic and applies to more sections on the page.

Here is an example of how you could eliminate some of the font related properties.  We can define them in a higher level element so the style will get applied to the entire page.

```
body {
  margin: 0;
  font-family: "Georgia", serif;
  font-size: 17px;
  color: black;
}

a {
  color: black;
}

h2 {
  margin-top: 0;
  margin-bottom: 0;
  font-size: 30px;
  font-weight: bold;
}
```

Now we don't have to worry about duplicating these properties across each main selector in your CSS.  As you continue working on future projects I would recommend starting to practice applying DRY.  It will pay huge dividends in the future!

**Comment by sunusinasser** [comment]
Thanks a lot For your Feedback i Make the changes you give it to me and boyd and i push to My github repo  if lov it to see it
